### ISSUE TITLE
Duplikaty w pieśniach powodują błędy w obsłudze

### ISSUE THREAD

**Issue by gg-mike** [hejmsdz/slidesui#2]
Kroki reprodukcji:
1. Przejdź do edycji jako tekst przyciskiem 📋.
2. Wpisz 2-krotnie `Oto Pan Bóg przyjdzie [1.1]`.
3. Zatwierdź przyciskiem ☑️.

Oczekiwany rezultat:
* Wybrana pieśń pojawi się 2 razy.

Obecny rezultat:
* Pieśń pojawia się raz, a jej numer jest równy ilości jej powtórzeń (w tym przypadku 2).
* Nie można zeskrolować do pierwszego wystąpienia pieśni.

**Comment by hejmsdz** [comment]
W wyszukiwarce możesz dotknąć/kliknąć znalezioną pieśń, wtedy zostanie dodana do listy i pojawi się koło niej znaczek ✔. Kiedy klikniesz ją drugi raz, zostanie usunięta. Masz jakiś pomysł na spójne zachowanie, gdy pieśni się powtarzają? Zastanawiam się, czy chcemy to uwzględniać w tym widoku i dostosować go pod taką rzadką sytuację, czy może po prostu usuwać duplikaty z pola edycji jako tekst.

**Comment by gg-mike** [comment]
W sumie poza taką sytuacją gdzie dwie msze św. są po sobie i mają podobne pieśni, to taki problem raczej nie wystąpi. Tak więc myślę, że można to usuwać z pola edycji (ewentualnie dodać jakiś komunikat dla użytkownika, że taka sytuacja ma miejsce).
